-- AVIATION EMPIRE DATABASE SCHEMA

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_login DATETIME
);

CREATE TABLE IF NOT EXISTS airlines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  airline_code TEXT UNIQUE NOT NULL,
  home_airport_code TEXT NOT NULL,
  balance REAL DEFAULT 50000000,
  image_score INTEGER DEFAULT 100,
  level INTEGER DEFAULT 1,
  total_points INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS aircraft_types (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  manufacturer TEXT NOT NULL,
  model TEXT NOT NULL,
  full_name TEXT NOT NULL,
  max_seats INTEGER NOT NULL,
  range_km INTEGER NOT NULL,
  new_price REAL NOT NULL,
  required_level INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS airports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  iata_code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  country TEXT NOT NULL,
  registration_prefix TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_airlines_user ON airlines(user_id);
b